import 'package:flutter/material.dart';
import '../models/culture_item.dart';

/// Données mock obsolètes - REMPLACÉES PAR LA BASE DE DONNÉES
@Deprecated('Obsolète : Utiliser exclusivement la base de données centrale via culture_data_providers et CultureRepository.')
abstract final class MockCultureStage1Data {
  // ── 1. ÉLÉMENT À LA UNE (ACCUEIL) ──────────────────────────────────────────
  static const CultureItem featuredItem = CultureItem(
    id: 'featured_soundiata',
    title: 'Soundiata Keïta & la Charte du Manden',
    subtitle: 'Le fondateur de l\'Empire du Mali et la proclamation de 1236',
    category: 'accueil',
    subCategory: 'personnages',
    description:
        'Découvrez l\'épopée du Lion du Manden, sa victoire décisive à Kirina en 1235 et la proclamation de l\'une des premières déclarations des droits humains à Kouroukan Fouga.',
    regionId: 'koulikoro',
    regionName: 'Koulikoro',
    tag: 'Épopée Majeure',
    icon: Icons.shield_rounded,
    imageUrl: 'assets/images/culture/personnages/soundiata.jpg',
    isFeatured: true,
    info: 'Lecture : 4 min',
  );

  // ── 2. GRANDS PERSONNAGES HISTORIQUES (DÉCOUVRIR) ──────────────────────────
  static const List<CultureItem> personnages = [
    CultureItem(
      id: 'perso_soundiata',
      title: 'Soundiata Keïta',
      subtitle: 'Le Lion du Manden & Fondateur de l\'Empire',
      category: 'decouvrir',
      subCategory: 'personnages',
      description:
          'Bâtisseur de l\'Empire du Mali et instigateur de la Charte de Kouroukan Fouga en 1236.',
      regionId: 'koulikoro',
      regionName: 'Koulikoro',
      tag: 'Mansa',
      icon: Icons.person_rounded,
      imageUrl: 'assets/images/culture/personnages/soundiata.jpg',
      info: '1190 – 1255',
    ),
    CultureItem(
      id: 'perso_mansa_moussa',
      title: 'Mansa Moussa',
      subtitle: 'L\'Empereur d\'Or & Mécène du Savoir',
      category: 'decouvrir',
      subCategory: 'personnages',
      description:
          'Souverain célèbre pour son pèlerinage de 1324 et l\'essor universel de Tombouctou et Gao.',
      regionId: 'tombouctou',
      regionName: 'Tombouctou',
      tag: 'Âge d\'Or',
      icon: Icons.account_balance_rounded,
      imageUrl: 'assets/images/culture/personnages/mansa_moussa.jpg',
      info: '1312 – 1337',
    ),
    CultureItem(
      id: 'perso_babemba',
      title: 'Babemba Traoré',
      subtitle: 'Roi du Kénédougou & Héros de Sikasso',
      category: 'decouvrir',
      subCategory: 'personnages',
      description:
          'Défenseur héroïque du Tata de Sikasso, symbole absolu de dignité patriotique.',
      regionId: 'sikasso',
      regionName: 'Sikasso',
      tag: 'Résistance',
      icon: Icons.security_rounded,
      imageUrl: 'assets/images/culture/personnages/babemba_traore.jpg',
      info: '1893 – 1898',
    ),
    CultureItem(
      id: 'perso_askia_mohammed',
      title: 'Askia Mohammed',
      subtitle: 'Grand Réformateur de l\'Empire Songhoï',
      category: 'decouvrir',
      subCategory: 'personnages',
      description:
          'Bâtisseur d\'une administration brillante et mécène de l\'Université de Sankoré.',
      regionId: 'gao',
      regionName: 'Gao',
      tag: 'Empire Songhoï',
      icon: Icons.history_edu_rounded,
      imageUrl: 'assets/images/culture/personnages/askia_mohammed.jpg',
      info: '1493 – 1528',
    ),
    CultureItem(
      id: 'perso_biton_coulibaly',
      title: 'Biton Coulibaly',
      subtitle: 'Fondateur du Royaume Bambara de Ségou',
      category: 'decouvrir',
      subCategory: 'personnages',
      description:
          'Créateur de l\'organisation militaire des Tônjons et de la puissance de Ségou.',
      regionId: 'segou',
      regionName: 'Ségou',
      tag: 'Royaume de Ségou',
      icon: Icons.military_tech_rounded,
      imageUrl: 'assets/images/culture/personnages/biton_coulibaly.jpg',
      info: '1712 – 1755',
    ),
  ];

  // ── 3. VILLES & VILLAGES (DÉCOUVRIR) ───────────────────────────────────────
  static const List<CultureItem> villes = [
    CultureItem(
      id: 'ville_djenne',
      title: 'Djenné',
      subtitle: 'La Cité Millénaire en Banco',
      category: 'decouvrir',
      subCategory: 'villes',
      description:
          'Joyau de la vallée du Bani, réputé pour sa prestigieuse architecture soudano-sahélienne.',
      regionId: 'mopti',
      regionName: 'Mopti',
      tag: 'UNESCO',
      icon: Icons.location_city_rounded,
      imageUrl: 'assets/images/culture/villes/djenne_ville.jpg',
      info: 'Fondée au IXe s.',
    ),
    CultureItem(
      id: 'ville_segou_koro',
      title: 'Ségou-Koro',
      subtitle: 'Le Berceau des 4 444 Balanzans',
      category: 'decouvrir',
      subCategory: 'villes',
      description:
          'L\'ancienne capitale royale où repose le roi Biton Coulibaly au bord du Djoliba.',
      regionId: 'segou',
      regionName: 'Ségou',
      tag: 'Cité Royale',
      icon: Icons.nature_people_rounded,
      imageUrl: 'assets/images/culture/villes/segou_koro.jpg',
      info: 'Bord du Niger',
    ),
    CultureItem(
      id: 'ville_bandiagara',
      title: 'Bandiagara & Falaise',
      subtitle: 'Les Villages Suspendus du Pays Dogon',
      category: 'decouvrir',
      subCategory: 'villes',
      description:
          'Villages séculaires accrochés au grès rouge, avec leurs Togunas et greniers ancestraux.',
      regionId: 'mopti',
      regionName: 'Mopti',
      tag: 'Pays Dogon',
      icon: Icons.terrain_rounded,
      imageUrl: 'assets/images/culture/villes/bandiagara_falaise.jpg',
      info: 'Falaise de 150 km',
    ),
    CultureItem(
      id: 'ville_tombouctou',
      title: 'Tombouctou',
      subtitle: 'La Cité des 333 Saints & des Manuscrits',
      category: 'decouvrir',
      subCategory: 'villes',
      description:
          'Carrefour transsaharien mythique ayant abrité les plus grands savants d\'Afrique.',
      regionId: 'tombouctou',
      regionName: 'Tombouctou',
      tag: 'Savoirs Sahéliens',
      icon: Icons.menu_book_rounded,
      imageUrl: 'assets/images/culture/villes/tombouctou_ville.jpg',
      info: 'Carrefour des caravanes',
    ),
    CultureItem(
      id: 'ville_sikasso',
      title: 'Sikasso',
      subtitle: 'Le Verger du Mali & la Cité du Kénédougou',
      category: 'decouvrir',
      subCategory: 'villes',
      description:
          'Capitale verdoyante et généreuse, gardienne des mémoires du roi Tiéba et Babemba.',
      regionId: 'sikasso',
      regionName: 'Sikasso',
      tag: 'Kénédougou',
      icon: Icons.park_rounded,
      imageUrl: 'assets/images/culture/villes/sikasso_ville.jpg',
      info: 'Terroir agricole',
    ),
  ];

  // ── 4. MONUMENTS HISTORIQUES (DÉCOUVRIR) ───────────────────────────────────
  static const List<CultureItem> monuments = [
    // Priorité Bamako (Capitale)
    CultureItem(
      id: 'monument_independance_bamako',
      title: 'Monument de l\'Indépendance',
      subtitle: 'Symbole de la Souveraineté du Mali (1960)',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Érigé au cœur de Bamako, ce monument célèbre l\'accession du Mali à l\'indépendance le 22 septembre 1960.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Symbole National',
      icon: Icons.flag_rounded,
      imageUrl: 'assets/images/culture/monuments/monument_independance.jpg',
      info: 'Bamako · 1960',
    ),
    CultureItem(
      id: 'monument_tour_afrique_bamako',
      title: 'Tour de l\'Afrique',
      subtitle: 'Phare du Panafricanisme & de l\'Unité',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Monument cylindrique colossal de 46 mètres évoquant un baobab et un minaret, dédié aux pères de l\'unité africaine.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Panafricanisme',
      icon: Icons.apartment_rounded,
      imageUrl: 'assets/images/culture/monuments/tour_afrique.jpg',
      info: 'Bamako · Faladié',
    ),
    CultureItem(
      id: 'monument_paix_bamako',
      title: 'Monument de la Paix',
      subtitle: 'Colombe Métallique de la Concorde',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Magnifique colombe stylisée aux ailes déployées, symbole de la réconciliation et du vivre-ensemble malien.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Paix & Vivre-Ensemble',
      icon: Icons.flutter_dash_rounded,
      imageUrl: 'assets/images/culture/monuments/monument_paix.jpg',
      info: 'Bamako · Hamdallaye',
    ),
    CultureItem(
      id: 'monument_armee_noire_bamako',
      title: 'Monument de l\'Armée Noire',
      subtitle: 'Hommage aux Tirailleurs & Héros Africains',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Statue de bronze honorant le sacrifice et le courage des soldats africains et tirailleurs pour la liberté.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Mémoire Militaire',
      icon: Icons.military_tech_rounded,
      imageUrl: 'assets/images/culture/monuments/monument_armee_noire.jpg',
      info: 'Bamako · 1924',
    ),
    CultureItem(
      id: 'monument_musee_national_bamako',
      title: 'Musée National du Mali',
      subtitle: 'Trésors Archéologiques & Masques Rituels',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Joyau en terre cuite stabilisée abritant des milliers d\'objets rituels, statuettes et textiles traditionnels.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Trésor Vivant',
      icon: Icons.museum_rounded,
      imageUrl: 'assets/images/culture/monuments/musee_national.jpg',
      info: 'Bamako · Parc Koulouba',
    ),
    CultureItem(
      id: 'monument_ciwara_senou_bamako',
      title: 'Masque Ciwara de Sénou',
      subtitle: 'Porte d\'Accueil & Dignité Paysanne',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Sculpture monumentale de l\'antilope mythique Ciwara, symbole de l\'ardeur au labeur et de la fertilité.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Emblème Sacré',
      icon: Icons.pets_rounded,
      imageUrl: 'assets/images/culture/monuments/ciwara_senou.jpg',
      info: 'Bamako · Sénou',
    ),
    CultureItem(
      id: 'monument_palais_culture_bamako',
      title: 'Palais de la Culture Amadou Hampâté Bâ',
      subtitle: 'L\'Agora des Arts au Bord du Djoliba',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Scène nationale des grands concerts, du théâtre et des contes, nommée en hommage au sage de Bandiagara.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Arts Vivants',
      icon: Icons.theater_comedy_rounded,
      imageUrl: 'assets/images/culture/monuments/palais_culture.jpg',
      info: 'Bamako · Badalabougou',
    ),
    CultureItem(
      id: 'monument_samory_toure_bamako',
      title: 'Monument Samory Touré',
      subtitle: 'Statue Équestre de la Résistance',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Statue équestre impériale en bronze d\'Almamy Samory Touré sur son cheval cabré à Sébénikoro.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Résistance Anticoloniale',
      icon: Icons.shield_rounded,
      imageUrl: 'assets/images/culture/monuments/monument_samory_toure_bamako/sam5.jpg',
      info: 'Bamako · Sébénikoro',
    ),
    CultureItem(
      id: 'monument_martyrs_bamako',
      title: 'Monument des Martyrs',
      subtitle: 'La Flamme Démocratique du 26 Mars 1991',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Stèle commémorative surplombant le fleuve Niger en mémoire des héros du mouvement démocratique.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Démocratie & Mémoire',
      icon: Icons.local_fire_department_rounded,
      imageUrl: 'assets/images/culture/monuments/monument_martyrs_bamako/mart10.jpg',
      info: 'Bamako · Pont des Martyrs',
    ),
    CultureItem(
      id: 'monument_kwame_nkrumah_bamako',
      title: 'Monument Kwamé Nkrumah',
      subtitle: 'Panafricanisme & Fraternité',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Buste en bronze et stèle commémorative en l\'honneur de Kwamé Nkrumah et de l\'alliance historique avec Modibo Keïta.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Panafricanisme',
      icon: Icons.public_rounded,
      imageUrl: 'assets/images/culture/monuments/monument_kwame_nkrumah_bamako/kk6.jpg',
      info: 'Bamako · Avenue Nkrumah',
    ),
    CultureItem(
      id: 'monument_cathedrale_bamako',
      title: 'Cathédrale du Sacré-Cœur',
      subtitle: 'Patrimoine en Grès Sahélien (1927)',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Édifice majestueux en pierres de taille locales néo-romanes africaines érigé au centre-ville.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Patrimoine Religieux',
      icon: Icons.church_rounded,
      imageUrl: 'assets/images/culture/monuments/monument_cathedrale_bamako/cat1.jpg',
      info: 'Bamako · 1927',
    ),
    CultureItem(
      id: 'monument_mosquee_bamako',
      title: 'Grande Mosquée de Bamako',
      subtitle: 'Minarets Blancs & Coupole Émeraude',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Cœur spirituel de Bamako situé à Dabanani, avec ses minarets élancés et ses arcades islamiques.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Architecture Religieuse',
      icon: Icons.mosque_rounded,
      imageUrl: 'assets/images/culture/monuments/mosquee_bamako.jpg',
      info: 'Bamako · Dabanani',
    ),
    CultureItem(
      id: 'monument_sogolon_bamako',
      title: 'Statue de Sogolon Kolonkan',
      subtitle: 'Matrimoine & Mémoire Mandingue',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Hommage à l\'héroïne royale du Mandé, sœur de Soundiata Keïta, garante de la concorde.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Matrimoine Mandingue',
      icon: Icons.woman_rounded,
      imageUrl: 'assets/images/culture/monuments/monument_sogolon_bamako/sog9.jpg',
      info: 'Bamako · Hamdallaye',
    ),
    CultureItem(
      id: 'monument_al_quouds',
      title: 'Monument Al-Qoods (Al-Qods)',
      subtitle: 'Dôme Doré & Arcades Orientales',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Dôme doré étincelant sur le rond-point d\'Hamdallaye ACI 2000, symbole de solidarité fraternelle.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Solidarité Fraternelle',
      icon: Icons.stars_rounded,
      imageUrl: 'assets/images/culture/monuments/monument_al_quouds/qu1.jpg',
      info: 'Bamako · ACI 2000',
    ),
    CultureItem(
      id: 'monument_maliba_bamako',
      title: 'Monument MaliBa',
      subtitle: 'Lettres 3D Vert Jaune Rouge',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Lettres géantes tricolores célébrant la fierté nationale et l\'attachement civique au Grand Mali.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Fierté Civique',
      icon: Icons.emoji_flags_rounded,
      imageUrl: 'assets/images/culture/monuments/monument_maliba_bamako/mb5.jpg',
      info: 'Bamako · Centre-ville',
    ),
    CultureItem(
      id: 'monument_obelisque_bamako',
      title: 'Obélisque de Bamako',
      subtitle: 'Stèle Monolithique en Pierre',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Obélisque commémoratif dominant le carrefour central près de la Place de la Liberté.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Cœur Civique',
      icon: Icons.account_balance_rounded,
      imageUrl: 'assets/images/culture/monuments/monument_obelisque_bamako/ob2.jpg',
      info: 'Bamako · Centre-ville',
    ),
    CultureItem(
      id: 'monument_Place_de_la_liberté',
      title: 'Place de la Liberté',
      subtitle: 'Esplanade Circulaire & Cœur Battant',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Grand forum urbain arboré entouré de fontaines et de colonnades reliant les artères historiques de Bamako.',
      regionId: 'bamako',
      regionName: 'Bamako',
      tag: 'Urbanisme & Histoire',
      icon: Icons.nature_people_rounded,
      imageUrl: 'assets/images/culture/monuments/monument_Place_de_la_liberté/lib1.jpg',
      info: 'Bamako · Centre-ville',
    ),

    // Monuments des autres régions
    CultureItem(
      id: 'monument_mosquee_djenne',
      title: 'Grande Mosquée de Djenné',
      subtitle: 'Le plus grand édifice en terre crue au monde',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Chef-d\'œuvre du style soudanais, entretenu chaque année lors de la fête du crépissage.',
      regionId: 'mopti',
      regionName: 'Mopti',
      tag: 'Monument UNESCO',
      icon: Icons.museum_rounded,
      imageUrl: 'assets/images/culture/monuments/mosquee_djenne.jpg',
      info: 'Architecture Banco',
    ),
    CultureItem(
      id: 'monument_tata_sikasso',
      title: 'Le Tata de Sikasso',
      subtitle: 'La Muraille de Résistance du Kénédougou',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Imposante forteresse de terre et de pierres ayant défendu la ville contre les sièges.',
      regionId: 'sikasso',
      regionName: 'Sikasso',
      tag: 'Fortification',
      icon: Icons.castle_rounded,
      imageUrl: 'assets/images/culture/monuments/tata_sikasso.jpg',
      info: 'XIXe siècle',
    ),
    CultureItem(
      id: 'monument_tombeau_askia',
      title: 'Tombeau pyramidal des Askia',
      subtitle: 'Symbole de la puissance de l\'Empire Songhoï',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Structure pyramidale majestueuse en banco édifiée à Gao par l\'empereur Askia Mohammed.',
      regionId: 'gao',
      regionName: 'Gao',
      tag: 'Gao Impérial',
      icon: Icons.architecture_rounded,
      imageUrl: 'assets/images/culture/monuments/tombeau_askia.jpg',
      info: 'Érigé en 1495',
    ),
    CultureItem(
      id: 'monument_djingareyber',
      title: 'Mosquée Djingareyber',
      subtitle: 'L\'œuvre commandée par Mansa Moussa en 1327',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Sanctuaire séculaire dessiné par le poète et architecte andalou Abou Ishaq es-Sahéli.',
      regionId: 'tombouctou',
      regionName: 'Tombouctou',
      tag: 'Patrimoine Majeur',
      icon: Icons.domain_rounded,
      imageUrl: 'assets/images/culture/monuments/mosquee_djingareyber.jpg',
      info: 'Bâtie en 1327',
    ),
    CultureItem(
      id: 'monument_sankore',
      title: 'Université & Mosquée de Sankoré',
      subtitle: 'Le Phare Universitaire de Tombouctou',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Cité du savoir médiéval ayant accueilli plus de 25 000 savants et étudiants.',
      regionId: 'tombouctou',
      regionName: 'Tombouctou',
      tag: 'Patrimoine Mondial UNESCO',
      icon: Icons.school_rounded,
      imageUrl: 'assets/images/culture/monuments/mosquee_sankore.jpg',
      info: 'XIVe siècle',
    ),
    CultureItem(
      id: 'monument_fort_medine',
      title: 'Fort de Médine',
      subtitle: 'Témoin des grandes batailles du Haut-Sénégal',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Site historique situé près de Kayes, au cœur des récits d\'El Hadj Oumar Tall.',
      regionId: 'kayes',
      regionName: 'Kayes',
      tag: 'Haut-Sénégal',
      icon: Icons.fort_rounded,
      imageUrl: 'assets/images/culture/monuments/fort_medine.jpg',
      info: 'Région de Kayes',
    ),
    CultureItem(
      id: 'segou',
      title: 'Ségou-Koro & Balanzans',
      subtitle: 'Cité Historique du Royaume Bambara',
      category: 'decouvrir',
      subCategory: 'monuments',
      description:
          'Ancienne capitale royale au bord du Djoliba et sanctuaire de Biton Coulibaly.',
      regionId: 'segou',
      regionName: 'Ségou',
      tag: 'Royaume Bambara',
      icon: Icons.palette_rounded,
      imageUrl: 'assets/images/culture/monuments/segou/segou_!.jpg',
      info: 'Région de Ségou',
    ),
  ];

  // ── 5. CONTES INTERACTIFS & TRADITIONS (CONTES) ───────────────────────────
  static const List<CultureItem> contes = [
    CultureItem(
      id: 'conte_lievre_hyene',
      title: 'Zoumana le Lièvre et Namori l\'Hyène',
      subtitle: 'La ruse de l\'esprit face à la force brute',
      category: 'contes',
      subCategory: 'contes_interactifs',
      description:
          'Une grande fable des veillées mandingues où la réflexion triomphe de la gourmandise.',
      regionId: null,
      regionName: 'Tout le Mali',
      tag: 'Conte Interactif',
      icon: Icons.auto_stories_rounded,
      info: 'Durée : 5 min',
    ),
    CultureItem(
      id: 'conte_wagadou_bida',
      title: 'La Légende du Serpent Wagadou Bida',
      subtitle: 'Le mythe fondateur de l\'Empire du Ghana',
      category: 'contes',
      subCategory: 'contes_interactifs',
      description:
          'L\'histoire du pacte sacré de Koumbi Saleh et de la pluie d\'or sur l\'ancien empire.',
      regionId: 'kayes',
      regionName: 'Kayes',
      tag: 'Récit Mythique',
      icon: Icons.psychology_alt_rounded,
      info: 'Récit des Griots',
    ),
    CultureItem(
      id: 'conte_forgeron_oiseau',
      title: 'Le Forgeron et l\'Oiseau du Djoliba',
      subtitle: 'Secret de la forge et respect des éléments',
      category: 'contes',
      subCategory: 'contes_interactifs',
      description:
          'Conte initiatique sur l\'alliance sacrée entre les maîtres du feu et la nature.',
      regionId: 'segou',
      regionName: 'Ségou',
      tag: 'Conte Initiatique',
      icon: Icons.local_fire_department_rounded,
      info: 'Tradition orale',
    ),
  ];

  // ── 6. DÉFIS & DEVINETTES (DÉFIS) ──────────────────────────────────────────
  static const List<CultureItem> defis = [
    CultureItem(
      id: 'defi_nda_baobab',
      title: '«   ! » — Les Énigmes du Baobab',
      subtitle: 'Devinettes traditionnelles Bambara',
      category: 'defis',
      subCategory: 'devinettes',
      description:
          'Répondez par «    sira » et élucidez les énigmes poétiques posées par nos aïeux.',
      regionId: null,
      regionName: 'Tout le Mali',
      tag: 'Jeu de Devinettes',
      icon: Icons.quiz_rounded,
      info: '10 Énigmes',
    ),
    CultureItem(
      id: 'defi_rois_empires',
      title: 'Le Grand Quiz des 3 Empires',
      subtitle: 'Ghana, Mali et Songhoï',
      category: 'defis',
      subCategory: 'devinettes',
      description:
          'Mesurez vos connaissances sur les dates clés, les dynasties et les grands héros du Mali.',
      regionId: null,
      regionName: 'Tout le Mali',
      tag: 'Quiz Culturel',
      icon: Icons.military_tech_rounded,
      info: 'Défi 10 questions',
    ),
    CultureItem(
      id: 'defi_chasseurs_manden',
      title: 'Les Maximes des Maîtres Chasseurs',
      subtitle: 'La sagesse de la confrérie des Dozo',
      category: 'defis',
      subCategory: 'devinettes',
      description:
          'Devinez le sens caché des proverbes et enseignements de la forêt sacrée.',
      regionId: 'koulikoro',
      regionName: 'Koulikoro',
      tag: 'Sagesse Dozo',
      icon: Icons.lightbulb_rounded,
      info: '5 Maximes',
    ),
  ];

  // ── FILTRE HELPERS ─────────────────────────────────────────────────────────
  static List<CultureItem> getFiltered({
    required List<CultureItem> source,
    String? regionId,
    String? query,
  }) {
    return source.where((item) {
      final matchesReg = item.matchesRegion(regionId);
      if (!matchesReg) return false;

      if (query == null || query.trim().isEmpty) return true;
      final q = query.trim().toLowerCase();
      return item.title.toLowerCase().contains(q) ||
          item.subtitle.toLowerCase().contains(q) ||
          item.description.toLowerCase().contains(q) ||
          item.regionName.toLowerCase().contains(q) ||
          item.tag.toLowerCase().contains(q);
    }).toList();
  }
}
